Emprunts * lireEmprunt (FILE *fe);
Emprunts * lireEnCours(FILE *fe);
int chargeEmprunts (Emprunts * t[], int nbmax, char *nom);
Liste insertionEnTete(Liste l, Emprunts *e);
Liste insertionEmprunt (Liste l, Emprunts *e) ;
Liste supprimerEnTete(Liste l);
Liste supprimerEmprunt(Liste l, Ouvrage o);
int insertionHistorique(Emprunts** t, Emprunts *e, int nbemp);
Booleen coteEstEmpruntee(Liste l, int cote);
Booleen estEmprunte(Ouvrage o, Lecteur** l, int nblec);
Emprunts * chercherEmprunt(Liste l, int cote);
int chercherEmprunteur(Lecteur** l, int nblec, Ouvrage o);
int compterEmprunts(Liste l);
void afficherUnEmprunt(Emprunts e, Booleen b, Ouvrage** touvr, int nbouvr, Lecteur** tlec, int nblec);
void afficherEmprunts(Emprunts** t, int nbemp, Ouvrage** touvr, int nbouvr, Lecteur** tlec, int nblec);
void afficherListeEmprunt(Liste l, Ouvrage** touvr, int nbouvr, Lecteur** tlec, int nblec);
void afficherEmpruntsEnCours(Lecteur** tlec, int nblec, Ouvrage** touvr, int nbouvr);
void sauvegarderEnmpruntsEnCours(Liste l, FILE *fe);
void viderListe(Liste l);